### ISSUE TITLE
documentation on how to use

### ISSUE THREAD

**Issue by ghost** [clemsciences/ohcr#1]
@clemsciences how can your code be used?
also can it extract lines?

**Comment by clemsciences** [comment]
Hey @christophered,
I'm refactoring the code in order to:
* be in English 
* add horizontal line detection.

Now, the code does not extract lines. It only extracts characters, but with a small modification, it could guess the lines where characters are.

**Comment by clemsciences** [comment]
So, it's in English, and I'm writing a tutorial to find lines in images.

**Comment by ghost** [comment]
@clemsciences thanks

**Comment by clemsciences** [comment]
What are actually your needs?

**Comment by ghost** [comment]
I'm just testing various `text line extraction` methods & tools that are available, to see which is more suitable to extract text lines from the scanned data I have. Later-on, the extracted lines will be used to train a new ocr model, either in Tesseract, ocropy or kraken.
Currently, [Ocropus3 ](https://github.com/nvlabs/ocropus3) got my interest, it uses deep learning to conduct page layout analysis & segmentation.
So, I think I found what I needed already.
Thank you

**Comment by clemsciences** [comment]
Ok! Well this repository is made for fun, so you won't get state-of-the-art algorithms.

At least your interest for this domain has made me work on this and it's good.

**Comment by ghost** [comment]
@clemsciences Thank you for your hard work!

**Comment by ghost** [comment]
I have tested the `seam carving` and it seems it's strength is in Handwriting line segmentation, while having some weakness in printed documents.
Thanks again.
